/**
 * Generate Supabase `Database` types from the migrations, offline.
 * Applies every migration to an in-process Postgres (PGlite) and introspects
 * the resulting schema — equivalent to `supabase gen types typescript`.
 *
 *   npm run db:types
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { createDatabase } from "../tests/support/pglite";

const OUT = path.resolve(import.meta.dirname, "../src/server/store/supabase/database.types.ts");

interface Column {
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: "YES" | "NO";
  column_default: string | null;
  ordinal_position: number;
}

const SCALAR: Record<string, string> = {
  uuid: "string", text: "string", date: "string", timestamptz: "string", inet: "string",
  int2: "number", int4: "number", int8: "number", numeric: "number", float4: "number", float8: "number",
  bool: "boolean", jsonb: "Json", json: "Json",
};

async function main() {
  const db = await createDatabase();
  const enums = await db.query<{ name: string; values: string[] }>(`
    select t.typname as name, array_agg(e.enumlabel order by e.enumsortorder) as values
    from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' group by t.typname order by t.typname`);
  const enumNames = new Set(enums.rows.map((e) => e.name));
  const columns = await db.query<Column>(`
    select c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default, c.ordinal_position
    from information_schema.columns c join information_schema.tables t on t.table_name = c.table_name and t.table_schema = c.table_schema
    where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
    order by c.table_name, c.ordinal_position`);

  const tsType = (c: Column): string => {
    const base = (udt: string): string => (enumNames.has(udt) ? `Database["public"]["Enums"]["${udt}"]` : (SCALAR[udt] ?? "unknown"));
    const t = c.udt_name.startsWith("_") ? `${base(c.udt_name.slice(1))}[]` : base(c.udt_name);
    return c.is_nullable === "YES" ? `${t} | null` : t;
  };

  const tables = new Map<string, Column[]>();
  for (const c of columns.rows) tables.set(c.table_name, [...(tables.get(c.table_name) ?? []), c]);

  const lines: string[] = [
    "// Generated by scripts/generate-db-types.ts from supabase/migrations. Do not edit.",
    "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
    "",
    "export type Database = {",
    '  __InternalSupabase: { PostgrestVersion: "12" };',
    "  public: {",
    "    Tables: {",
  ];
  for (const [table, cols] of tables) {
    lines.push(`      ${table}: {`);
    lines.push("        Row: {");
    for (const c of cols) lines.push(`          ${c.column_name}: ${tsType(c)};`);
    lines.push("        };");
    lines.push("        Insert: {");
    for (const c of cols) lines.push(`          ${c.column_name}${c.is_nullable === "YES" || c.column_default !== null ? "?" : ""}: ${tsType(c)};`);
    lines.push("        };");
    lines.push("        Update: {");
    for (const c of cols) lines.push(`          ${c.column_name}?: ${tsType(c)};`);
    lines.push("        };");
    lines.push("        Relationships: [];");
    lines.push("      };");
  }
  lines.push("    };");
  lines.push("    Views: { [_ in never]: never };");
  lines.push("    Functions: {");
  lines.push("      sgk_increment_rate_counters: { Args: { p_keys: string[]; p_window_seconds: number }; Returns: number[] };");
  lines.push("      sgk_replace_sandbox: { Args: { p_org: string; p_dataset: Json }; Returns: undefined };");
  lines.push('      sgk_activity_stats: { Args: { p_org: string; p_env: Database["public"]["Enums"]["sgk_environment"]; p_since: string }; Returns: Json };');
  lines.push('      sgk_create_organization: { Args: { p_name: string; p_kind: Database["public"]["Enums"]["sgk_organization_kind"] }; Returns: string };');
  lines.push("      sgk_verify_audit_chain: { Args: { p_org: string }; Returns: number | null };");
  lines.push("      sgk_is_member: { Args: { org: string }; Returns: boolean };");
  lines.push("    };");
  lines.push("    Enums: {");
  for (const e of enums.rows) lines.push(`      ${e.name}: ${e.values.map((v) => JSON.stringify(v)).join(" | ")};`);
  lines.push("    };");
  lines.push("    CompositeTypes: { [_ in never]: never };");
  lines.push("  };");
  lines.push("};");
  lines.push("");
  writeFileSync(OUT, lines.join("\n"));
  console.log(`Wrote ${tables.size} tables and ${enums.rows.length} enums to ${path.relative(process.cwd(), OUT)}`);
  await db.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
